---
title: "ECO353 Data Project #1 - NBA Player Salaries and Team Winning Percentage (%)"
author: Jared Madarang and Jeffrey Chu
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message=FALSE, warning=FALSE)
```


```{r, include = FALSE}
install.packages("tidyverse")
install.packages("jtools")
install.packages("collapse")
install.packages("RCurl")
install.packages("corrplot")
install.packages("dplyr")
install.packages("ineq")
install.packages("DescTools")
library(tidyverse)
library(jtools)
library(collapse)
library(RCurl)
library(corrplot)
library(dplyr)
library(ineq)
library(DescTools)
```


## Data Collection: Merging NBA Player Salaries and Team Winning Percentage (%)

**NBA Player Salaries (YEARSTART-YEAREND)**

```{r}
url <- getURL("https://raw.githubusercontent.com/jeffreychu48/ECO353/refs/heads/main/salaries_1985to2018.csv")
nba.salaries <- read.csv(text = url)
nba.salaries <- nba.salaries %>% select(team, playerid, salary, seasonstart)
nba.salaries %>% arrange(desc(salary)) %>% head()
```

**NBA Team Winning Percentage (YEARSTART-YEAREND)**

```{r}
url <- getURL("https://raw.githubusercontent.com/jeffreychu48/ECO353/refs/heads/main/nba_team_win.csv")
nba.teamwin <- read.csv(text = url)
nba.teamwin <- nba.teamwin %>% select(team, record, winpercent, seasonstart)
head(nba.teamwin)
```

**Team Salary Distribution**

Gini coefficient by team and seasonstart

```{r}
gini.allyears <- nba.salaries %>% 
  group_by(team, seasonstart) %>%   
  summarise(gini = Gini(salary, na.rm = TRUE), 
            .groups = "drop") %>% 
  arrange(seasonstart, team) 

gini.allyears <- gini.allyears %>% arrange(desc(gini))

gini.allyears %>% head()

```

Gini Coefficient over Time

```{r}
ggplot(data = gini.allyears, aes(x = seasonstart, y = gini, color = team)) +
  geom_point(size = 2) +
  geom_smooth(method="lm", se = TRUE, color="black") +
  ggtitle("Gini Salary Coefficient over Time")
```



**Team Salary Distribution and Team Wins**

Gini coefficient by team and seasonstart


















